package com.modula.ui;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

import javafx.scene.image.Image;

/**
 * The application mark, at the sizes a window manager might ask for.
 *
 * <p>Several sizes rather than one large image: a taskbar downscaling 512 to 16 produces mush, and
 * the small marks are drawn differently on purpose — below 32 pixels they drop the dim outer ring,
 * which at that size turns to mud rather than reading as a weaker signal.
 *
 * <p>Generated by {@code scripts/make-icon.py} from the same geometry the tray icon draws, so the
 * dock entry and the tray entry are one mark.
 */
public final class AppIcons {

    private static final int[] SIZES = {16, 24, 32, 48, 64, 128, 256, 512};

    private static List<Image> cached;

    private AppIcons() {}

    /** Every size, largest last. Empty if the resources are missing — an icon is never worth a crash. */
    public static List<Image> all() {
        if (cached == null) {
            List<Image> images = new ArrayList<>(SIZES.length);
            for (int size : SIZES) {
                Image image = load(size);
                if (image != null) {
                    images.add(image);
                }
            }
            cached = List.copyOf(images);
        }
        return cached;
    }

    /** One size, for a place that wants a specific one — the About panel, say. Null if missing. */
    public static Image at(int size) {
        return load(size);
    }

    private static Image load(int size) {
        try (InputStream in = AppIcons.class.getResourceAsStream("/com/modula/icons/icon-" + size + ".png")) {
            return in == null ? null : new Image(in);
        } catch (Exception e) {
            return null;
        }
    }
}
