#!/usr/bin/env python3
"""
Generates the Modula icon: branding/modula-icon.svg and the PNG set.

The geometry lives here, once, and both outputs derive from it — an SVG kept by hand beside PNGs
rendered from different numbers is a design source of record that lies, which is worse than none.

Run from the project root:  python3 scripts/make-icon.py   (needs Pillow)

The mark is TrayIconRenderer's, so the dock icon and the tray icon are one mark. The tray draws at
SCALE 1.0 because it has no tile to sit inside; everything else about the shape is shared.
"""

import math
import os

# --- the mark -------------------------------------------------------------------------------
SPAN = 44.0  # half-sweep either side of the axis, degrees
RING = lambda n: 0.17 + 0.155 * n  # ring radius as a fraction of the canvas
STROKE = 0.078
DOT = 0.155
SCALE = 0.72  # the mark's share of a tiled icon, leaving platform-safe padding

# --- the kit's palette ----------------------------------------------------------------------
AMBER = (0xFF, 0xB4, 0x54)  # dial
CABIN = (0x0B, 0x0C, 0x0E)  # ground
SURF = (0x14, 0x16, 0x1A)  # surface
LINE = (0x23, 0x26, 0x2C)  # line
OUTER_WEIGHT = 0.42  # the outer ring is the same amber, weaker — not a second colour

TILE_RADIUS = 112 / 512  # rounded-square corner, as a fraction of the side
SIZES = [16, 24, 32, 48, 64, 128, 256, 512]
TWO_RING_FLOOR = 32  # below this the dim ring turns to mud, so the mark keeps one


def blend(fg, bg, a):
    return tuple(round(f * a + b * (1 - a)) for f, b in zip(fg, bg))


def hexof(rgb):
    return "#%02X%02X%02X" % rgb


# --- SVG ------------------------------------------------------------------------------------


def arc_path(c, r, mid):
    a0, a1 = math.radians(mid - SPAN), math.radians(mid + SPAN)
    return "M%.2f,%.2f A%.2f,%.2f 0 0 1 %.2f,%.2f" % (
        c + r * math.cos(a0), c + r * math.sin(a0), r, r,
        c + r * math.cos(a1), c + r * math.sin(a1),
    )


def svg():
    side, c = 512, 256.0
    paths = []
    for n in (1, 2):
        r = side * RING(n) * SCALE
        colour = hexof(AMBER if n == 1 else blend(AMBER, SURF, OUTER_WEIGHT))
        for mid in (0, 180):
            paths.append(
                '  <path d="%s" fill="none" stroke="%s" stroke-width="%.2f" stroke-linecap="round"/>'
                % (arc_path(c, r, mid), colour, side * STROKE * SCALE)
            )
    return """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <!--
    Modula — the Night Dial mark. GENERATED by scripts/make-icon.py; edit that, not this.

    One idea, taken from the kit: the dial is emitting light and everything else is reflecting it.
    The tile is the cabin — a cool near-black, never a warm charcoal, which would put the amber into
    the surface — and the mark is the only lit thing on it.

    Amber is a budget. In the interface it is spent on the frequency; here there is no frequency to
    compete with, so the mark IS the spend: full weight at the centre, weaker at the edge, so the
    signal reads as radiating and falling off rather than as a target. The outer ring is the same
    amber mixed toward the ground, not a second colour.
  -->
  <defs>
    <radialGradient id="cabin" cx="50%%" cy="34%%" r="78%%">
      <stop offset="0%%" stop-color="%s"/>
      <stop offset="100%%" stop-color="%s"/>
    </radialGradient>
  </defs>

  <rect width="512" height="512" rx="%.0f" ry="%.0f" fill="url(#cabin)"/>
  <!-- The kit's line token, so the tile keeps an edge on a light desktop. -->
  <rect x="1.25" y="1.25" width="509.5" height="509.5" rx="%.0f" ry="%.0f"
        fill="none" stroke="%s" stroke-width="2.5"/>

%s

  <circle cx="256" cy="256" r="%.2f" fill="%s"/>
</svg>
""" % (
        hexof(SURF), hexof(CABIN),
        side * TILE_RADIUS, side * TILE_RADIUS,
        side * TILE_RADIUS - 1.25, side * TILE_RADIUS - 1.25, hexof(LINE),
        "\n".join(paths),
        side * DOT / 2 * SCALE, hexof(AMBER),
    )


# --- PNG ------------------------------------------------------------------------------------


def render(size, tile=True, rings=None, mono=None, supersample=4):
    from PIL import Image, ImageDraw

    rings = rings if rings is not None else ((1, 2) if size >= TWO_RING_FLOOR else (1,))
    s = size * supersample
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    c = s / 2

    if tile:
        for i in range(int(s * 0.80), 0, -1):
            t = i / (s * 0.80)
            d.ellipse(
                [c - i * 1.25, c - i * 1.45, c + i * 1.25, c + i * 1.05],
                fill=blend(SURF, CABIN, (1 - t) ** 1.6) + (255,),
            )
        base = Image.new("RGBA", (s, s), CABIN + (255,))
        base.alpha_composite(img)
        img = base
        mask = Image.new("L", (s, s), 0)
        ImageDraw.Draw(mask).rounded_rectangle([0, 0, s - 1, s - 1], radius=int(s * TILE_RADIUS), fill=255)
        img.putalpha(mask)
        d = ImageDraw.Draw(img)
        d.rounded_rectangle(
            [supersample, supersample, s - 1 - supersample, s - 1 - supersample],
            radius=int(s * TILE_RADIUS) - supersample,
            outline=LINE + (255,),
            width=round(2.5 * supersample),
        )

    ground = SURF if tile else CABIN
    scale = SCALE if tile else 1.0
    width = s * STROKE * scale
    for n in rings:
        r = s * RING(n) * scale
        weight = 1.0 if n == 1 else OUTER_WEIGHT
        colour = (mono + (255,)) if mono else blend(AMBER, ground, weight) + (255,)
        for mid in (0, 180):
            # A round-capped, round-joined arc, stamped along its centreline: PIL's own arc has
            # square ends and its width grows inward from the bounding box.
            steps = max(24, int(r * SPAN / 8))
            for i in range(steps + 1):
                a = math.radians(mid - SPAN + (2 * SPAN) * i / steps)
                x, y = c + r * math.cos(a), c + r * math.sin(a)
                d.ellipse([x - width / 2, y - width / 2, x + width / 2, y + width / 2], fill=colour)

    dot = s * DOT / 2 * scale
    d.ellipse([c - dot, c - dot, c + dot, c + dot], fill=(mono + (255,)) if mono else AMBER + (255,))
    return img.resize((size, size), Image.LANCZOS)


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    branding = os.path.join(root, "branding")
    icons = os.path.join(root, "src", "main", "resources", "com", "modula", "icons")
    os.makedirs(branding, exist_ok=True)
    os.makedirs(icons, exist_ok=True)

    with open(os.path.join(branding, "modula-icon.svg"), "w") as f:
        f.write(svg())

    for size in SIZES:
        image = render(size)
        image.save(os.path.join(branding, "modula-icon-%d.png" % size))
        image.save(os.path.join(icons, "icon-%d.png" % size))
    print("wrote modula-icon.svg and %d PNGs" % len(SIZES))


if __name__ == "__main__":
    main()
